### ISSUE TITLE
Releases organization

### ISSUE THREAD

**Issue by rchastain** [mse-org/mseide-msegui#13]
Hello gentlemen of the MSE team!

I think it would be good that we have a discussion about organization and presentation  of releases.

Here are my ideas. Please let me know what you think of it.

The main idea is that we need a template for releases. I speak of the text which is displayed for each release. It should be clear, simple, in good english, and used for all releases, so that we have an uniform presentation.

Is it necessary to reproduce for each release the general description of MSEide+MSEgui? Isn't it the function of the README? For the text of the release, we could keep only the description of what is new in this version.

Fred suggested in a private discussion to create a README.md from the README.txt. I think it's a good idea.

A last thing. It would be good to have somewhere a clear summary of all modifications that we made, since the last version released by Martin. In principle, it's the function of commits, but commits are not always readable. Often there are many unessential modifications that hide the important things.

Have a nice day.

Roland

**Comment by rchastain** [comment]
> A last thing. It would be good to have somewhere a clear summary of all modifications that we made, since the last version released by Martin. In principle, it's the function of commits, but commits are not always readable. Often there are many unessential modifications that hide the important things.
> 

I see that Fred has updated VERSION.TXT (only for v5.0.0). It's good, but maybe it isn't enough to say "Compatible with fpc 3.2.0". We need to know exactly what has been changed. And of course it should be done for v5.1.0 too.

**Comment by rchastain** [comment]
For the general description of MSEide+MSEgui, we already have this text (from Martin?):

> MSEide is a Rapid Application Development IDE for platform independent rich GUI applications in the Pascal language. It comes with its own GUI toolkit called MSEgui.

**Comment by fredvs** [comment]
Hello Roland.
I am not a king in marketing things.
You do it perfectly, in everything you touch, so I agree for all what you noticed.

Fre;D

**Comment by circular17** [comment]
> A last thing. It would be good to have somewhere a clear summary of all modifications that we made, since the last version released by Martin. In principle, it's the function of commits, but commits are not always readable. Often there are many unessential modifications that hide the important things.

Agreed. For example in LazPaint I put the modifications in the release text. That's summarized and reorganized. As you say there are some modifications I don't mention because either it is too much of a detail, or that in the end that's not really a change. For example if I make many changes for one thing. Also reorganizing is important because commits are not necessary in a logical order.

**Comment by rchastain** [comment]
Thank you guys for your answers.
I will prepare something and come back to present it to you.
Fred, maybe I would need your help to know exactly what modification has been made for FPC 3.2 compatibility.

**Comment by fredvs** [comment]
> Fred, maybe I would need your help to know exactly what modification has been made for FPC 3.2 compatibility.

I fear that circular17 knows much better than me what was done.

**Comment by fredvs** [comment]
Oops, it is about compatibility for FPC version 3.2.0, ha, ok (not compatibility with classes).

OK, I will re-jump into the commits to refresh my mind for all this.

**Comment by fredvs** [comment]
- 25 Apr 2019 for compatibility >= 3.2.0 Graeme:

  Added in needed units: 
  `{$interfaces corba}`

  Changed all `iifilink` with `iificlient`, like this:

  `function tgraphdataedit.getdefaultifilink: iifilink; override;`
  with
  `function tgraphdataedit.getdefaultifilink: iificlient; override;
`

- 25 Jul 2019 for compatibility >= 3.2.0:

   Fixed MSEide designer method parser (did add hidden 'self' part).


- 28 Jul 2019 for compatibility >= 3.3.1 Sven:

    Fixed Parameters flags.


- 23 Mar 2020 for compatibility >= 3.3.1:

   Fixed compatibility with mse-stat files. 

- 16 Apr 2020 for compatibility >= 3.2.0

  Fixed in msesystypes.pas threadty declaration on Windows 64 bit.

- 18 Apr 2020 for compatibility >= 3.2.0
  
  Added some tweaked fpc files for compatibility.

- 19 Apr 2020 for compatibility >= 3.2.0
  
   Fixed typo in base64.pp of mclasses.

- 01 May 2020 for compatibility >= 3.2.0
  
   Renamed all last fpc tweaked files into mse_***.pas in /fpccompatibility. Adapted code in msegui for it.

- 16 May 2020 for compatibility >= 3.2.0
  
    Fixed error: msechart.pas(1252,9) Error: Asm: [pxor mem??,xmmreg1]

**Comment by rchastain** [comment]
OK guys, I close the issue.
Thank you Fred for the summary of modifications.
See you soon!
