### ISSUE TITLE
Can't build documentation

### ISSUE THREAD

**Issue by milen-prg** [mse-org/mseide-msegui#84]
Windows 11 64bit, MSEide v5.10.0.

In folder _C:\mseide\mseide-msegui-5.10.0\help\fpdoc_ I tried: `C:\mseide\mseide-msegui-5.10.0\help\fpdoc>fpdoc --project=msegui-docs-project.xml`

```
FPDoc - Free Pascal Documentation Tool
Version 3.2.2 [2021/05/15]
(c) 2000 - 2003 Areca Systems GmbH / Sebastian Guenther, sg@freepascal.org
(c) 2005 - 2012 various FPC contributors

Parsing used unit "mseclasses" with commandLine "../../lib/common/kernel/mseclasses.pas -Fu../lib/common/* -Fu../lib/common/kernel/linux -Fi../lib/common/kernel"
Parsing used unit "mseglob" with commandLine "../../lib/common/kernel/mseglob.pas -Fu../lib/common/* -Fu../lib/common/kernel/linux -Fi../lib/common/kernel"
Parsing used unit "mseerr" with commandLine "../.

Parsing used unit "msestockobjects" with commandLine "../../lib/common/kernel/msestockobjects.pas -Fu../lib/common/* -Fu../lib/common/kernel/linux -Fi../lib/common/kernel"
Exception at 00488D25: EFileNotFoundError:
../../lib/common/kernel/msestockobjects.pas.

The process stops with ERROR:
Exception at 00488D25: EFileNotFoundError:
../../lib/common/kernel/msestockobjects.pas.
```

**Comment by fredvs** [comment]
Hello.

Hum, I did not try to make that documentation.
That help folder is very old, sure it must be updated. 

But about the error:
```
 EFileNotFoundError:
../../lib/common/kernel/msestockobjects.pas.
```
 **msestockobjects.pas**, since msegui version 5.x,  is now located in:
**/mseide-msegui/lib/common/lang_consts/msestockobjects.pas**

Maybe changing it in **msegui-docs-project.xml** could fix it.

But Roland can help you better than me.

Fre;D

**Comment by fredvs** [comment]
Re-hello.
Here documentation done by [Roland](https://codeberg.org/rchastain/msedoc) with fpdoc:
https://msegui.net/doc/fpdoc/index.html

And here done with pasdoc: 
https://msegui.net/doc/pasdoc/index.html

@rchastain: Maybe we could commit your code in /mseide-msegui/help

**Comment by rchastain** [comment]
I generated the documentation a long time ago and didn't remember how I did it. I will take a look ASAP.

**Comment by milen-prg** [comment]
@fredvs , I'm new with this framework/ide and because I fully agree with this:
[https://github.com/mse-org/mseide-msegui/blob/main/help/fpdoc/README.txt](https://github.com/mse-org/mseide-msegui/blob/main/help/fpdoc/README.txt)

> API documentation is a vital part of any framework's success. So we welcome others to contribute to this effort so that MSEgui can finally have some real API documentation.

I expected this (i.e. several rows description of each component/class):
[https://github.com/mse-org/mseide-msegui/blob/main/help/fpdoc/docview_msegui_docs.png](https://github.com/mse-org/mseide-msegui/blob/main/help/fpdoc/docview_msegui_docs.png)

Unfortunately, suggested by you links are completely not enough to start to work with MSEgui.

**Comment by fredvs** [comment]
About documentation how to use MSEgui, you may take a look at the Wiki:
https://github.com/mse-org/mseide-msegui/wiki/MSE-Wiki

But we all agree that the weak link of MSEgui is its lack of documentation.

**Comment by fredvs** [comment]
The file **help/fpdoc/msegui-docs-project.xml** was fixed in last commits: https://github.com/mse-org/mseide-msegui/commit/5bb3c70b42bff594c75e146f61fdbc1593249946 and https://github.com/mse-org/mseide-msegui/commit/7a9a081af495561abd158dc71512c70af96dc944

Doing this in the directory /mseide-msegui/help/fpdoc/:

`> fpdoc --project=msegui-docs-project.xml`

will produce **msegui.ipf**

But I dont know with what program it must be open, I was not able to open it with docview, it seems that it can not read **.ipf** files (or I miss something).
