### ISSUE TITLE
Exception 'Unable to open file ...' when opening a project

### ISSUE THREAD

**Issue by milen-prg** [mse-org/mseide-msegui#86]
As last versions have no precompiled binaries, I try to compile the new source (mseide-msegui-5.10.4) with old mseide_win64/mseide.exe. But when open (as in documentation) the C:\mseide\mseide-msegui-5.10.4\apps\ide\mseide.prj, this error appears:

![image](https://github.com/mse-org/mseide-msegui/assets/59639866/90f30b6f-c828-4af8-9ffa-7ee90b479c5e)

After "Continue" (as in the "documentation") it compiles and produces mseide.exe and its seems that works, only when open it in its About is shown the old version (must be 5.10.4):
 
![image](https://github.com/mse-org/mseide-msegui/assets/59639866/d3e95e87-c059-4ba1-96cf-21d2f650427f)

Maybe, this all is normal, but I'm beginner and I feel it is not all ok.

**Comment by fredvs** [comment]
Hello milen-prg.

>C:\mseide\mseide-msegui-5.10.4\apps\ide\mseide.prj, this error appears:

Aaaargh, it is the file from my history that should not be there for the release.
The message say that this file in the history could not be found (of course it was from my pc).
You may ignore the message but I agree it is not a good "Welcome to MSEgui".

I will fix that asap (tonight), thanks to note it.
[EDIT] Fixed in last commit: https://github.com/mse-org/mseide-msegui/commit/795b48658d7204b72eeaa3cca8ceac2ebc9efe83

>, only when open it in its About is shown the old version (must be 5.10.4):

Hum, strange, how did you compile mseide, did you set the MSEdir with the last source?
Did you compile MSEide via MSEide v 5.10 (then you need to check in menu Settings/Configure MSEide the  ${MSEDIR})?
[EDIT]
 > I try to compile the new source (mseide-msegui-5.10.4) with old mseide_win64/mseide.exe.

Ha, OK so you should check the directory of **MSEDIR**:

![msedir](https://github.com/mse-org/mseide-msegui/assets/3421249/4301a0ae-1c56-4b24-a221-7ff5cb08249f)

If you use the script from the readme.md, before to run the command, make sure you are in the directory of the new msegui source.

Here it is ok:
 
![about_mseide_win64](https://github.com/mse-org/mseide-msegui/assets/3421249/b8fdfa38-c19d-4600-82a6-5a7e6bc76925)

**Comment by rchastain** [comment]
> After "Continue" (as in the "documentation") it compiles and produces mseide.exe and its seems that works, only when open it in its About is shown the old version (must be 5.10.4):

I think it's because you didn't change **MSEDIR** value in _Settings/Configure MSEide_. So the IDE has been compiled using MSEgui 5.10.2.

It is said in the documentation.

**Comment by rchastain** [comment]
> I will fix that asap (tonight), thanks to note it. [EDIT] Fixed in last commit: [795b486](https://github.com/mse-org/mseide-msegui/commit/795b48658d7204b72eeaa3cca8ceac2ebc9efe83)

I am curious. How did you do it? Did you edit manually the PRJ file?

A good habit is to close all files before you exit MSEide, particularly when it is a project of the repository. (Advice given by Martin.)

**Comment by rchastain** [comment]
Fred, there is a word badly written in _README.md_ (**direcory**).

**Comment by fredvs** [comment]
>I am curious. How did you do it? Did you edit manually the PRJ file?

Yes, I did it like this.
I did not catch yet how to disable the history of files in the prj.
There are options in Project-Option about what to store into the prj but I did not see how to disable history.

**Comment by fredvs** [comment]
> Fred, there is a word badly written in _README.md_ (**direcory**).

Ooops, fixed in commit https://github.com/mse-org/mseide-msegui/commit/04533bd5e52fcc0fb7ddaf1a4623106beb512063

**Comment by fredvs** [comment]
>As last versions have no precompiled binaries,

Yes, MSEide 5.10. (the application) himself does no need the fixes of MSEgui 5.10.2 and 5.10.4.

At end of release-page: https://github.com/mse-org/mseide-msegui/releases/tag/5.10.4

**For the release of binary MSEide, please use the assets of release 5.10.0. (no change in MSEide for MSEgui 5.10.4.)
See assets at end of page:**
https://github.com/mse-org/mseide-msegui/releases/tag/5.10.0

Anyway, it is ok to rebuild MSEide with last MSEgui source.

**Comment by milen-prg** [comment]
@fredvs , in compilation I really was selected the old version source in settings ${MSEDIR} and open the mseide.prj from the new source. When I set before the compilation the ${MSEDIR} to the new source, the version in About is correct.
Thank, you!

**Comment by fredvs** [comment]
@milen-prg : I am happy that you find solution.
(And thanks to note that mseide.prj was full of history.)
