### ISSUE TITLE
[Sieghard branch] mseide desepears after create new project

### ISSUE THREAD

**Issue by codz01** [mse-org/mseide-msegui#89]
Hi
i find a problem in sieghard branch , to reproduce :
create new project from templates , then create new folder after you press ok button mseide will desepears 

system : windows7 , fpc 3.2.2 32bits 

 
![bug](https://github.com/mse-org/mseide-msegui/assets/10813427/9b191eda-2337-49bf-8f4c-09ae0b5f6127)

**Comment by fredvs** [comment]
Hello.

Hum, other problem surely related, see here: https://github.com/mse-org/mseide-msegui/discussions/87#discussioncomment-9287530
Sieghard answered via mailing list:

----------------------------------------

_Indeed, there's one problem with the "newdialogs" I found, but didn't have
the time and opportunity to test on other platforms but my old Linux box
running the openbox window manager: Everytime one dismisses such a dialog,
it also blinks the main (or maybe calling) form of the application, and
sometimes it stays off altogether, only complaining about a "not decorated"
problem.
Investigating that, I found a "waitfordecoration" call in the
"kernel/linux/mseguiintf.pas" unit which seems to be superfluous, as
everything seems to work flawlessly without it, without any recognizable
problems concerning window decorations.
Sadly, I wasn't able yet  to find anythimg relevant about the blinking
issue, as it's nearly impossible to follow the intircately convoluted path
of execution through the pertaining, deeply entrenched and constantly
traversed, window control functions. It's literally so that after setting a
breakpoint there at some interesting point, you cannot run the program
normally any more. Most any action opening any smallish subwindow will ALSO
use that function, triggering the breakpoint and obviating the attempted
action...
But the culprit has to be something in conjunction with producing the
window decorations, as the dialogs work correctly with window decorations
disabled. Which isn't really useful, as this hampers one of the main goals
of the "newdialogs", providing free and self-controlled positioning and
sizing.
I'll continue to pursue the issue further, but I'm afraid that it will take
ample time yet. I'll report here what I can find, and of course, when the
issue was solved, may have been solved..._

-------------------------------------------

**Comment by fredvs** [comment]
Hello.

Sieghard's fixes are committed-pushed in the sieghard branch: https://github.com/mse-org/mseide-msegui/commit/ade2ce1803e2a213f8015c5ea898e382792f91e0

Tests are welcome!

**Comment by codz01** [comment]
it works now 
by the way , what is the features that has been added into dialogs components , in this branch ?

**Comment by fredvs** [comment]
>by the way , what is the features that has been added into dialogs components , in this branch ?

https://github.com/mse-org/mseide-msegui/discussions/87#discussioncomment-9205943
